### PR TITLE
Looker 6 docker setup

### PR DESCRIPTION
**Pull request by troyharvey**
Thanks to the work of @deangelo-llooker and @dev-head, we are running Looker 6 in Docker in production on Rancher. This PR is a copy-paste of our internal Looker setup minus the production Rancher Compose configuration.

* Uses Ubuntu LTS
* Uses OpenJDK 8
* Adds support for the new Looker jar API
* Adds the work that @dev-head [did in this gist](https://gist.github.com/dev-head/9ba1dfe3b3a038aa479e4288d8062157) to the main looker_docker repo.
* Adds Docker Compose setup and simplifies the Getting Started guide.
* Cleaned up the README to make it more user-friendly for someone just looking to take Looker & Docker for a test drive.

### CODE REVIEW

**Comment by troyharvey** [comment]
Hey Looker maintainers 👋 I just got a support request about this branch. Folks are using it out in the wild. Gentle nudge to consider merging it. 😄 I just updated it to default to `6.12`.

**Comment by troyharvey** [comment]
cc @stevekrouse @mslovich @jkaster @jbandhauer @stalbot @haarthi

**Comment by mslovich** [comment]
I believe Troy meant to tag @deangelo-llooker rather than me here...

**Comment by benpoliquin** [comment]
@wilg @willdougadams This is extremely helpful! +1 to getting this merged.

**Comment by troyharvey** [comment]
Please close if there are no plans to merge.

**Pull request closed without merging**
